version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: petclinic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - petclinic-net

  petclinic:
    build: .
    container_name: petclinic-app
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - petclinic-net

volumes:
  mysql_data:

networks:
  petclinic-net:
